In [6]:
!kaggle datasets download ankitbansal06/retail-orders-f orders.csv

usage: kaggle [-h] [-v] [-W]
              {competitions,c,datasets,d,kernels,k,models,m,files,f,config}
              ...
kaggle: error: unrecognized arguments: orders.csv

In [5]:
pip install kaggle

Collecting kaggle
  Downloading kaggle-1.6.17.tar.gz (82 kB)
                                              0.0/82.7 kB ? eta -:--:--
     ----                                     10.2/82.7 kB ? eta -:--:--
     ----                                     10.2/82.7 kB ? eta -:--:--
     ----------------------------           61.4/82.7 kB 656.4 kB/s eta 0:00:01
     -------------------------------------- 82.7/82.7 kB 664.7 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.10 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: bleach in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from bleach->kaggle) (23.0)
Requirement already satisfied: webencodings in c:\users\admin\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\admin\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (setup.py): started
  Building wheel for kaggle (setup.py): finished with status 'done'
  Created wheel for kaggle: filename=kaggle-1.6.17-py3-none-any.whl size=105802 sha256=86282cffecae58f6e84abdb25d5d09dfe61918cd984ae920aeb458a15256517f
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\ff\55\fb\b27a466be754d2a06ffe0e37b248d844f090a63b51becea85d
Successfully built kaggle
Installing collected packages: kaggle
Successfully installed kaggle-1.6.17
Note: you may need to restart the kernel to use updated packages.

In [9]:
import kaggle

In [11]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\Admin\Desktop\Python

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 236kB/s]
100%|##########| 200k/200k [00:00<00:00, 236kB/s]

In [4]:
import zipfile as ZP

In [11]:
ZP.extractall("orders.zip", path = "C:\Users\Admin\Desktop\Python")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (765344700.py, line 1)

In [6]:
dir(ZP)

['BZIP2_VERSION',
 'BadZipFile',
 'BadZipfile',
 'CompleteDirs',
 'DEFAULT_VERSION',
 'FastLookup',
 'LZMACompressor',
 'LZMADecompressor',
 'LZMA_VERSION',
 'LargeZipFile',
 'MAX_EXTRACT_VERSION',
 'Path',
 'PyZipFile',
 'ZIP64_LIMIT',
 'ZIP64_VERSION',
 'ZIP_BZIP2',
 'ZIP_DEFLATED',
 'ZIP_FILECOUNT_LIMIT',
 'ZIP_LZMA',
 'ZIP_MAX_COMMENT',
 'ZIP_STORED',
 'ZipExtFile',
 'ZipFile',
 'ZipInfo',
 '_CD64_CREATE_VERSION',
 '_CD64_DIRECTORY_RECSIZE',
 '_CD64_DIRECTORY_SIZE',
 '_CD64_DISK_NUMBER',
 '_CD64_DISK_NUMBER_START',
 '_CD64_EXTRACT_VERSION',
 '_CD64_NUMBER_ENTRIES_THIS_DISK',
 '_CD64_NUMBER_ENTRIES_TOTAL',
 '_CD64_OFFSET_START_CENTDIR',
 '_CD64_SIGNATURE',
 '_CD_COMMENT_LENGTH',
 '_CD_COMPRESSED_SIZE',
 '_CD_COMPRESS_TYPE',
 '_CD_CRC',
 '_CD_CREATE_SYSTEM',
 '_CD_CREATE_VERSION',
 '_CD_DATE',
 '_CD_DISK_NUMBER_START',
 '_CD_EXTERNAL_FILE_ATTRIBUTES',
 '_CD_EXTRACT_SYSTEM',
 '_CD_EXTRACT_VERSION',
 '_CD_EXTRA_FIELD_LENGTH',
 '_CD_FILENAME_LENGTH',
 '_CD_FLAG_BITS',
 '_CD_INTERNAL_FILE_ATTRIBUTES',
 '_CD_LOCAL_HEADER_OFFSET',
 '_CD_SIGNATURE',
 '_CD_TIME',
 '_CD_UNCOMPRESSED_SIZE',
 '_DD_SIGNATURE',
 '_ECD_COMMENT',
 '_ECD_COMMENT_SIZE',
 '_ECD_DISK_NUMBER',
 '_ECD_DISK_START',
 '_ECD_ENTRIES_THIS_DISK',
 '_ECD_ENTRIES_TOTAL',
 '_ECD_LOCATION',
 '_ECD_OFFSET',
 '_ECD_SIGNATURE',
 '_ECD_SIZE',
 '_EXTRA_FIELD_STRUCT',
 '_EndRecData',
 '_EndRecData64',
 '_FH_COMPRESSED_SIZE',
 '_FH_COMPRESSION_METHOD',
 '_FH_CRC',
 '_FH_EXTRACT_SYSTEM',
 '_FH_EXTRACT_VERSION',
 '_FH_EXTRA_FIELD_LENGTH',
 '_FH_FILENAME_LENGTH',
 '_FH_GENERAL_PURPOSE_FLAG_BITS',
 '_FH_LAST_MOD_DATE',
 '_FH_LAST_MOD_TIME',
 '_FH_SIGNATURE',
 '_FH_UNCOMPRESSED_SIZE',
 '_MASK_COMPRESSED_PATCH',
 '_MASK_COMPRESS_OPTION_1',
 '_MASK_ENCRYPTED',
 '_MASK_STRONG_ENCRYPTION',
 '_MASK_USE_DATA_DESCRIPTOR',
 '_MASK_UTF_FILENAME',
 '_SharedFile',
 '_Tellable',
 '_ZipDecrypter',
 '_ZipWriteFile',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_ancestry',
 '_check_compression',
 '_check_zipfile',
 '_crctable',
 '_dedupe',
 '_difference',
 '_extract_text_encoding',
 '_gen_crc',
 '_get_compressor',
 '_get_decompressor',
 '_parents',
 '_strip_extra',
 'binascii',
 'bz2',
 'compressor_names',
 'contextlib',
 'crc32',
 'error',
 'importlib',
 'io',
 'is_zipfile',
 'itertools',
 'lzma',
 'main',
 'os',
 'pathlib',
 'posixpath',
 'shutil',
 'sizeCentralDir',
 'sizeEndCentDir',
 'sizeEndCentDir64',
 'sizeEndCentDir64Locator',
 'sizeFileHeader',
 'stat',
 'stringCentralDir',
 'stringEndArchive',
 'stringEndArchive64',
 'stringEndArchive64Locator',
 'stringFileHeader',
 'struct',
 'structCentralDir',
 'structEndArchive',
 'structEndArchive64',
 'structEndArchive64Locator',
 'structFileHeader',
 'sys',
 'threading',
 'time',
 'zlib']

In [13]:
import zipfile as zp

# Path to the zip file
zip_file_path = 'C:\Users\Admin\Desktop\Python\orders.csv'

# Directory where you want to extract the contents
extract_dir = 'C:\Users\Admin\Desktop\Python'

# Open the zip file in read mode
with zp.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents into the specified directory
    zip_ref.extractall(extract_dir)

print(f"Files extracted to {extract_dir}")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (227853812.py, line 4)

In [18]:
import zipfile as zp

# Path to the zip file
zip_file_path = r'C:\Users\Admin\Desktop\Python\orders.csv.zip'

# Directory where you want to extract the contents
extract_dir = r'C:\Users\Admin\Desktop\Python'

# Open the zip file in read mode
with zp.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents into the specified directory
    zip_ref.extractall(extract_dir)

print(f"Files extracted to {extract_dir}")

Files extracted to C:\Users\Admin\Desktop\Python

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('orders.csv')
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [5]:
print(df.head())

   Order Id  Order Date       Ship Mode    Segment        Country  \
0         1  2023-03-01    Second Class   Consumer  United States
1         2  2023-08-15    Second Class   Consumer  United States
2         3  2023-01-10    Second Class  Corporate  United States
3         4  2022-06-18  Standard Class   Consumer  United States
4         5  2022-07-13  Standard Class   Consumer  United States

              City       State  Postal Code Region         Category  \
0        Henderson    Kentucky        42420  South        Furniture
1        Henderson    Kentucky        42420  South        Furniture
2      Los Angeles  California        90036   West  Office Supplies
3  Fort Lauderdale     Florida        33311  South        Furniture
4  Fort Lauderdale     Florida        33311  South  Office Supplies

  Sub Category       Product Id  cost price  List Price  Quantity  \
0    Bookcases  FUR-BO-10001798         240         260         2
1       Chairs  FUR-CH-10000454         600         730         3
2       Labels  OFF-LA-10000240          10          10         2
3       Tables  FUR-TA-10000577         780         960         5
4      Storage  OFF-ST-10000760          20          20         2

   Discount Percent
0                 2
1                 3
2                 5
3                 2
4                 5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [13]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%Y-%m-%d')
df.dtypes

Order Id                     int64
Order Date          datetime64[ns]
Ship Mode                   object
Segment                     object
Country                     object
City                        object
State                       object
Postal Code                  int64
Region                      object
Category                    object
Sub Category                object
Product Id                  object
cost price                   int64
List Price                   int64
Quantity                     int64
Discount Percent             int64
dtype: object

In [15]:
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [16]:
df['Ship Mode'] = df['Ship Mode'].fillna('Default Class')
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [17]:
df.rename(columns={'Order Id': 'Order_Id', 'Order Date': 'Order_Date','Ship Mode': 'Ship_Mode', 'Postal Code': 'Postal_Code'
                  ,'Sub Category': 'Sub_Category', 'Product Id': 'Product_Id', 'cost price': 'cost_price', 
                   'List Price': 'List_Price', 'Discount Percent': 'Discount_Percent'}, inplace=True)
df.dtypes

Order_Id                     int64
Order_Date          datetime64[ns]
Ship_Mode                   object
Segment                     object
Country                     object
City                        object
State                       object
Postal_Code                  int64
Region                      object
Category                    object
Sub_Category                object
Product_Id                  object
cost_price                   int64
List_Price                   int64
Quantity                     int64
Discount_Percent             int64
dtype: object

In [21]:
df[['Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub_Category', 'Product_Id'] = df[['Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub_Category', 'Product_Id']].apply(lambda x: x.str.rstrip())

SyntaxError: invalid syntax (3353543765.py, line 1)

In [22]:
df[['Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub_Category', 'Product_Id']] = df[['Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub_Category', 'Product_Id']].apply(lambda x: x.str.rstrip())

In [23]:
df

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [24]:
df['Discount'] = df['List_Price'] * (df['Discount_Percent'] / 100)

# Calculate the Sale Price column
df['Sale_price'] = df['List_Price'] - df['Discount']

# Calculate the Profit column
df['Profit'] = df['Sale_price'] - df['cost_price']

# updated DataFrame
df

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,Discount,Sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [25]:
df1 = df[['Order_Id', 'Order_Date', 'Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Postal_Code', 'Region', 'Category'  ]]  # orders_details
df2 = df[['Order_Id', 'Sub_Category', 'Product_Id', 'cost_price', 'List_Price', 'Quantity', 'Discount_Percent', 'Discount', 'Sale_price', 'Profit']]  # Product_details

# Save the DataFrames to CSV files
df1.to_csv('orders_details.csv', index=False)  # Saving df1 to a CSV file without the index column
df2.to_csv('Product_details.csv', index=False)

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
                                              0.0/45.0 kB ? eta -:--:--
     -----------------                      20.5/45.0 kB 682.7 kB/s eta 0:00:01
     -------------------------------------- 45.0/45.0 kB 739.0 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pymysql

In [8]:
df1 = pd.read_csv('orders_details.csv')
df1

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies
...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies

In [9]:
df2 = pd.read_csv('Product_details.csv')
df2

,Order_Id,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,Discount,Sale_price,Profit
0,1,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...
9989,9990,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [11]:
from sqlalchemy import create_engine

# MySQL connection
engine = create_engine('mysql+pymysql://root:mysql@localhost/retail_order')

df1.to_sql('order_details', engine, if_exists='replace', index=False)
df2.to_sql('Product_details', engine, if_exists='replace', index=False)

C:\Users\Admin\AppData\Local\Temp\ipykernel_24780\288932182.py:7: UserWarning: The provided table name 'Product_details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df2.to_sql('Product_details', engine, if_exists='replace', index=False)

9994

In [1]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.1.0-cp311-cp311-win_amd64.whl (16.1 MB)
                                              0.0/16.1 MB ? eta -:--:--
                                              0.0/16.1 MB ? eta -:--:--
                                              0.1/16.1 MB 1.6 MB/s eta 0:00:10
     -                                        0.7/16.1 MB 7.5 MB/s eta 0:00:03
     ---                                      1.4/16.1 MB 11.4 MB/s eta 0:00:02
     ----                                     1.9/16.1 MB 12.3 MB/s eta 0:00:02
     ------                                   2.7/16.1 MB 13.4 MB/s eta 0:00:01
     --------                                 3.5/16.1 MB 14.9 MB/s eta 0:00:01
     ----------                               4.2/16.1 MB 15.8 MB/s eta 0:00:01
     ------------                             5.0/16.1 MB 16.0 MB/s eta 0:00:01
     --------------                           5.8/16.1 MB 16.8 MB/s eta 0:00:01
     ----------------                         6.5/16.1 MB 17.3 MB/s eta 0:00:01
     -----------------                        7.2/16.1 MB 17.7 MB/s eta 0:00:01
     -------------------                      8.0/16.1 MB 17.5 MB/s eta 0:00:01
     ---------------------                    8.7/16.1 MB 17.9 MB/s eta 0:00:01
     -----------------------                  9.3/16.1 MB 18.1 MB/s eta 0:00:01
     ------------------------                 9.7/16.1 MB 18.3 MB/s eta 0:00:01
     -------------------------               10.6/16.1 MB 19.9 MB/s eta 0:00:01
     ---------------------------             11.3/16.1 MB 19.9 MB/s eta 0:00:01
     -----------------------------           12.1/16.1 MB 20.5 MB/s eta 0:00:01
     -------------------------------         12.8/16.1 MB 19.8 MB/s eta 0:00:01
     --------------------------------        13.6/16.1 MB 19.8 MB/s eta 0:00:01
     ----------------------------------      14.2/16.1 MB 19.8 MB/s eta 0:00:01
     ------------------------------------    15.0/16.1 MB 19.8 MB/s eta 0:00:01
     ------------------------------------    15.0/16.1 MB 19.8 MB/s eta 0:00:01
     -------------------------------------   15.4/16.1 MB 18.2 MB/s eta 0:00:01
     --------------------------------------  16.0/16.1 MB 17.7 MB/s eta 0:00:01
     --------------------------------------  16.1/16.1 MB 17.7 MB/s eta 0:00:01
     --------------------------------------- 16.1/16.1 MB 16.8 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.1.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import mysql.connector
import pandas as pd

# Step 1: Connect to MySQL
connection = mysql.connector.connect(
    host="localhost",  # e.g., 'localhost'
    user="root",
    password="mysql",
    database="retail_order"
)

# Step 2: Execute the SQL query and load data into a DataFrame
query1 = "SELECT * FROM order_details"
query2 = "SELECT * FROM Product_details"
df1 = pd.read_sql(query1, connection)
df2 = pd.read_sql(query2, connection)

# Step 3: Display the DataFrame
print(df1.head())
print(df2.head())

# Step 4: Close the connection
connection.close()

   Order_Id  Order_Date       Ship_Mode    Segment        Country  \
0         1  2023-03-01    Second Class   Consumer  United States
1         2  2023-08-15    Second Class   Consumer  United States
2         3  2023-01-10    Second Class  Corporate  United States
3         4  2022-06-18  Standard Class   Consumer  United States
4         5  2022-07-13  Standard Class   Consumer  United States

              City       State  Postal_Code Region         Category
0        Henderson    Kentucky        42420  South        Furniture
1        Henderson    Kentucky        42420  South        Furniture
2      Los Angeles  California        90036   West  Office Supplies
3  Fort Lauderdale     Florida        33311  South        Furniture
4  Fort Lauderdale     Florida        33311  South  Office Supplies
   Order_Id Sub_Category       Product_Id  cost_price  List_Price  Quantity  \
0         1    Bookcases  FUR-BO-10001798         240         260         2
1         2       Chairs  FUR-CH-10000454         600         730         3
2         3       Labels  OFF-LA-10000240          10          10         2
3         4       Tables  FUR-TA-10000577         780         960         5
4         5      Storage  OFF-ST-10000760          20          20         2

   Discount_Percent  Discount  Sale_price  Profit
0                 2       5.2       254.8    14.8
1                 3      21.9       708.1   108.1
2                 5       0.5         9.5    -0.5
3                 2      19.2       940.8   160.8
4                 5       1.0        19.0    -1.0

C:\Users\Admin\AppData\Local\Temp\ipykernel_21300\3225474373.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(query1, connection)
C:\Users\Admin\AppData\Local\Temp\ipykernel_21300\3225474373.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query2, connection)

In [1]:
pip install streamlit mysql-connector-python pandas

Collecting streamlit
  Downloading streamlit-1.41.1-py2.py3-none-any.whl (9.1 MB)
                                              0.0/9.1 MB ? eta -:--:--
                                              0.0/9.1 MB ? eta -:--:--
                                              0.1/9.1 MB 991.0 kB/s eta 0:00:10
     --                                       0.6/9.1 MB 5.0 MB/s eta 0:00:02
     -----                                    1.3/9.1 MB 9.0 MB/s eta 0:00:01
     --------                                 2.0/9.1 MB 11.5 MB/s eta 0:00:01
     -----------                              2.7/9.1 MB 12.1 MB/s eta 0:00:01
     --------------                           3.3/9.1 MB 13.1 MB/s eta 0:00:01
     -----------------                        4.0/9.1 MB 14.4 MB/s eta 0:00:01
     --------------------                     4.8/9.1 MB 14.5 MB/s eta 0:00:01
     ------------------------                 5.6/9.1 MB 15.5 MB/s eta 0:00:01
     ---------------------------              6.3/9.1 MB 16.1 MB/s eta 0:00:01
     ------------------------------           7.0/9.1 MB 16.6 MB/s eta 0:00:01
     ----------------------------------       7.8/9.1 MB 16.5 MB/s eta 0:00:01
     -------------------------------------    8.5/9.1 MB 17.0 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 17.1 MB/s eta 0:00:01
     ---------------------------------------- 9.1/9.1 MB 16.2 MB/s eta 0:00:00
Requirement already satisfied: mysql-connector-python in c:\users\admin\anaconda3\lib\site-packages (9.1.0)
Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (1.5.3)
Collecting altair<6,>=4.0 (from streamlit)
  Downloading altair-5.5.0-py3-none-any.whl (731 kB)
                                              0.0/731.2 kB ? eta -:--:--
     ------------------------------------  727.0/731.2 kB 23.1 MB/s eta 0:00:01
     ------------------------------------- 731.2/731.2 kB 15.7 MB/s eta 0:00:00
Collecting blinker<2,>=1.0.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Collecting cachetools<6,>=4.0 (from streamlit)
  Downloading cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (8.0.4)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (1.24.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (23.0)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (10.4.0)
Collecting protobuf<6,>=3.20 (from streamlit)
  Downloading protobuf-5.29.2-cp310-abi3-win_amd64.whl (434 kB)
                                              0.0/434.5 kB ? eta -:--:--
     ------------------------------------- 434.5/434.5 kB 13.7 MB/s eta 0:00:00
Requirement already satisfied: pyarrow>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Collecting rich<14,>=10.14.0 (from streamlit)
  Downloading rich-13.9.4-py3-none-any.whl (242 kB)
                                              0.0/242.4 kB ? eta -:--:--
     ------------------------------------- 242.4/242.4 kB 14.5 MB/s eta 0:00:00
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (4.6.3)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.1.6)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading GitPython-3.1.43-py3-none-any.whl (207 kB)
                                              0.0/207.3 kB ? eta -:--:--
     ------------------------------------- 207.3/207.3 kB 12.3 MB/s eta 0:00:00
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
                                              0.0/6.9 MB ? eta -:--:--
     -----                                    0.9/6.9 MB 27.7 MB/s eta 0:00:01
     ---------                                1.6/6.9 MB 25.3 MB/s eta 0:00:01
     -------------                            2.3/6.9 MB 20.8 MB/s eta 0:00:01
     ----------------                         2.9/6.9 MB 20.4 MB/s eta 0:00:01
     --------------------                     3.6/6.9 MB 21.0 MB/s eta 0:00:01
     ------------------------                 4.2/6.9 MB 19.3 MB/s eta 0:00:01
     ----------------------------             4.9/6.9 MB 19.7 MB/s eta 0:00:01
     --------------------------------         5.7/6.9 MB 20.1 MB/s eta 0:00:01
     -------------------------------------    6.4/6.9 MB 20.4 MB/s eta 0:00:01
     ---------------------------------------  6.9/6.9 MB 20.1 MB/s eta 0:00:01
     ---------------------------------------- 6.9/6.9 MB 19.2 MB/s eta 0:00:00
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (6.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: jinja2 in c:\users\admin\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\admin\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)
  Downloading narwhals-1.19.1-py3-none-any.whl (260 kB)
                                              0.0/260.6 kB ? eta -:--:--
     ------------------------------------- 260.6/260.6 kB 16.7 MB/s eta 0:00:00
Collecting typing-extensions<5,>=4.3.0 (from streamlit)
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
                                              0.0/62.7 kB ? eta -:--:--
     ---------------------------------------  61.4/62.7 kB ? eta -:--:--
     ---------------------------------------- 62.7/62.7 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Installing collected packages: typing-extensions, smmap, protobuf, narwhals, cachetools, blinker, rich, pydeck, gitdb, gitpython, altair, streamlit
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.3
    Uninstalling typing_extensions-4.6.3:
      Successfully uninstalled typing_extensions-4.6.3
Successfully installed altair-5.5.0 blinker-1.9.0 cachetools-5.5.0 gitdb-4.0.11 gitpython-3.1.43 narwhals-1.19.1 protobuf-5.29.2 pydeck-0.9.1 rich-13.9.4 smmap-5.0.1 streamlit-1.41.1 typing-extensions-4.12.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import streamlit as st

In [3]:
import streamlit as st
import pandas as pd
import mysql.connector

# Function to fetch data from MySQL
def get_data_from_mysql():
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="mysql",
        database="retail_order"
    )
    
    query = "SELECT * FROM retail_order.product_details"  # Modify this query as needed
    data = pd.read_sql(query, connection)  # Use pandas to execute SQL query and load data into a DataFrame
    
    connection.close()
    return data

# Streamlit interface
def main():
    st.title("MySQL Data in Streamlit")

    # Fetch data from MySQL
    data = get_data_from_mysql()

    # Display data in Streamlit
    st.subheader("Data from MySQL Database:")
    st.dataframe(data)

if __name__ == "__main__":
    main()

2024-12-26 22:44:40.068 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-26 22:44:40.528
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2024-12-26 22:44:40.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
C:\Users\Admin\AppData\Local\Temp\ipykernel_14340\1941263210.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, connection)  # Use pandas to execute SQL query and load data into a DataFrame
2024-12-26 22:44:40.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-26 22:44:40.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-26 22:44:40.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-26 22:44:40.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.